table dim_date
	lineageTag: 21a0147e-3c1f-4df4-b422-3f7fbfb8109e
	dataCategory: Time

	column DateKey
		dataType: int64
		isHidden
		formatString: #,0
		lineageTag: 0a0b1a94-4052-4562-b8cc-dd733e3f8824
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = User

	column Date
		dataType: dateTime
		isKey
		formatString: dd MMM yyyy
		lineageTag: db8e5949-35d3-4353-932c-d8857a242970
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = User

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: b9d4f158-a477-4372-bf37-29748d998b3b
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = User

	column Quarter
		dataType: string
		lineageTag: b9ccc53b-de44-40e2-aff2-7f2641214ef8
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = User

	column MonthNumber
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 571eeb8d-3e31-44d5-819a-55e2cf56719c
		summarizeBy: none
		sourceColumn: MonthNumber

		annotation SummarizationSetBy = User

	column MonthName
		dataType: string
		lineageTag: e1cc8b60-31b9-413a-a163-24d536f6e1a5
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: MonthNumber

		annotation SummarizationSetBy = User

	column YearMonth
		dataType: string
		lineageTag: e81ea235-fca5-4c52-8fd9-49a04b88a0a7
		summarizeBy: none
		sourceColumn: YearMonth

		annotation SummarizationSetBy = User

	column Weekday
		dataType: string
		lineageTag: 59b686d9-f523-4bab-a3f9-fe094d52642b
		summarizeBy: none
		sourceColumn: Weekday

		annotation SummarizationSetBy = User

	column IsWeekend
		dataType: boolean
		lineageTag: b53e7595-6bb6-4941-a216-2d7bbd8a09f8
		summarizeBy: none
		sourceColumn: IsWeekend

		annotation SummarizationSetBy = User

	partition dim_date = m
		mode: import
		source =
				let
				    Raw = Csv.Document(
				        File.Contents(DataFolder & "\dim_date.csv"),
				        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
				    ),
				    Promoted = Table.PromoteHeaders(Raw, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {
				            {"DateKey", Int64.Type},
				            {"Date", type date},
				            {"Year", Int64.Type},
				            {"Quarter", type text},
				            {"MonthNumber", Int64.Type},
				            {"MonthName", type text},
				            {"YearMonth", type text},
				            {"Weekday", type text},
				            {"IsWeekend", type logical}
				    })
				in
				    Typed

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

